name: client_meta
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  basic_utils: ^5.7.0
  crypto: ^3.0.3
  encrypt: ^5.0.3
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.2.2
  grpc: ^3.2.4
  logger: ^2.3.0
  pointycastle: ^3.9.1
  server_grpc:
    path: ../server_grpc
  dartz: ^0.10.1
  equatable: ^2.0.5
  provider: ^6.1.2
  flutter_svg: ^2.0.10+1
  nav_service: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg/