name: client_meta
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  basic_utils: ^5.7.0
  crypto: ^3.0.3
  encrypt: ^5.0.3
  flutter:
    sdk: flutter
  flutter_secure_storage: ^4.2.1
  grpc: ^3.2.4
  logger: ^2.3.0
  pointycastle: ^3.9.1
  server_grpc:
    path: ../server_grpc

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
